services:
  - type: web
    name: rma-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rma-database
          property: connectionString

databases:
  - name: rma-database
    databaseName: rma_system
    user: rma_user